version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G204
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocyclo
          - gosec
          - unparam
        path: _test\.go
      - linters:
          - govet
        text: fieldalignment
      - linters:
          - govet
        text: shadow
      - linters:
          - govet
        text: nilness
      - linters:
          - prealloc
        text: Consider pre-allocating
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
