# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

git:
  tag_sort: -version:refname
  prerelease_suffix: "-"

builds:
  - main: ./cmd/proj_descr
    id: "proj_descr"
    binary: proj_descr
    ldflags:
      - -s -w
      - -X github.com/jvzantvoort/tmux-project/version.Version={{.Version}}
      - -X github.com/jvzantvoort/tmux-project/version.Commit={{.Commit}}
      - -X github.com/jvzantvoort/tmux-project/version.BuildTime={{.Date}}
    goos:
      - linux
      - darwin
  - main: ./cmd/proj_info
    id: "proj_info"
    binary: proj_info
    ldflags:
      - -s -w
      - -X github.com/jvzantvoort/tmux-project/version.Version={{.Version}}
      - -X github.com/jvzantvoort/tmux-project/version.Commit={{.Commit}}
      - -X github.com/jvzantvoort/tmux-project/version.BuildTime={{.Date}}
    goos:
      - linux
      - darwin
  - main: ./cmd/resume
    id: "resume"
    binary: resume
    ldflags:
      - -s -w
      - -X github.com/jvzantvoort/tmux-project/version.Version={{.Version}}
      - -X github.com/jvzantvoort/tmux-project/version.Commit={{.Commit}}
      - -X github.com/jvzantvoort/tmux-project/version.BuildTime={{.Date}}
    goos:
      - linux
      - darwin
  - main: ./cmd/tmux-project
    id: "tmux-project"
    binary: tmux-project
    ldflags:
      - -s -w
      - -X github.com/jvzantvoort/tmux-project/version.Version={{.Version}}
      - -X github.com/jvzantvoort/tmux-project/version.Commit={{.Commit}}
      - -X github.com/jvzantvoort/tmux-project/version.BuildTime={{.Date}}
    goos:
      - linux
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      tmux-project_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - tmux-project-update
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
