---
type: PROJECTTYPE
description: PROJECTTYPE
directory: "{{.HomeDir}}/{{.ProjectType}}/{{.Name}}"
pattern: ^.*$
setupactions:
  - echo {{.Name}}
repos: []
# - url:
#   destination:
#   branch:
targets:
  - name: default.env
    destination: "{{.Name}}.env"
    mode: 644
  - name: default.rc
    destination: "{{.Name}}.rc"
    mode: 644
