#!/bin/bash

[[ "$-" =~ i ]] || return
[[ -z "$TMUX" ]] && return

#shellcheck disable=SC2155
declare -x SESSIONNAME=$(tmux display-message -p '#S'  2>/dev/null)

#shellcheck disable=SC1090
if [ -f "$HOME/.tmux.d/${SESSIONNAME}.env" ]
then
  source  "$HOME/.tmux.d/${SESSIONNAME}.env"
fi
