#!/bin/bash

if [[ -n "$TMUX" ]]
then
  SESSIONNAME="$(tmux display-message -p '#S'  2>/dev/null)"
  export SESSIONNAME

  #shellcheck disable=SC1090
  if [ -f "$HOME/.tmux.d/${SESSIONNAME}.env" ]
  then
    source  "$HOME/.tmux.d/${SESSIONNAME}.env"
  fi

  #shellcheck disable=SC2164
  function pcd() { cd "$PROJDIR/$1"; }
fi
