#!/bin/bash

if [[ -n "$TMUX" ]]; then

  SESSIONNAME="$(tmux display-message -p '#S'  2>/dev/null)"
  HISTFILE="${HOME}/.bash_history_${SESSIONNAME}"

  export SESSIONNAME HISTFILE

  if [[ -r "$HOME/.tmux.d/${SESSIONNAME}.json" ]]; then
    if command -v jq &> /dev/null; then
      #shellcheck disable=SC2002
      SESSIONTYPE="$(cat "$HOME/.tmux.d/${SESSIONNAME}.json" | jq -r .type)"
    fi
  fi

  #shellcheck disable=SC1090
  if [[ -f "$HOME/.tmux.d/${SESSIONNAME}.env" ]]; then
    source "$HOME/.tmux.d/${SESSIONNAME}.env"
  fi

  #shellcheck disable=SC1090
  if [[ -n "${SESSIONTYPE}" ]]; then
    if [[ -f "$HOME/.tmux.d/${SESSIONTYPE}.shared" ]]; then
      source "$HOME/.tmux.d/${SESSIONTYPE}.shared"
    fi
  fi

  # if "${PROJDIR}/.pcd.rc" exists its contenst is read as semicolon delimited
  # fields:
  #
  #  <shortname>;directory
  #
  # PROJDIR is replaced by its environment variable
  #
  # Example:
  #
  #  foo;PROJDIR/bar
  #
  # "pcd foo" will change directory to "${PROJDIR}/bar"
  #
  #shellcheck disable=SC2164
  function pcd()
  {
    # empty
    if [[ -z "$1" ]]; then
      cd "${PROJDIR}"
      return
    fi

    __name="$1"

    # check for a config file and an entry
    if [[ -f "${PROJDIR}/.pcd.rc" ]]; then
      dst="$(awk -v pat="${__name}" -F";" '$1 == pat { print $2 }' "${PROJDIR}/.pcd.rc" | sed "s,PROJDIR,${PROJDIR},")"
      if [[ -n "${dst}" ]]; then
        cd "${dst}"
        return
      fi
    fi

    # subdir in project
    cd "$PROJDIR/${__name}";

  }

  _pcd_autocomplete() {
    local cur opts
    cur="${COMP_WORDS[COMP_CWORD]}"

    # Collect folder names in $PROJDIR
    opts="$(find "$PROJDIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"

    # Collect entries from .pcd.rc if it exists
    if [[ -f "${PROJDIR}/.pcd.rc" ]]; then
      opts+=" $(awk -F';' '{print $1}' "$PROJDIR/.pcd.rc")"
    fi

    #shellcheck disable=SC2207
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
  }

  complete -F _pcd_autocomplete pcd

fi
